---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-management
  template:
    metadata:
      labels:
        app: tenant-management
    spec:
      serviceAccountName: KUSTOMIZE_SHARED_SVC_ACCOUNT_NAME
      automountServiceAccountToken: true
      containers:
      - name: tenant-management
        image: KUSTOMIZE_IMAGE
        ports:
        - containerPort: 8002
          name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-management-service
spec:
  selector:
    app: tenant-management
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8002
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant-management-service-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: KUSTOMIZE_API_HOST
      http:
        paths:
          - path: /auth-info
            pathType: Prefix
            backend:
              service:
                name: tenant-management-service
                port:
                  number: 80
          - path: /tenants
            pathType: Prefix
            backend:
              service:
                name: tenant-management-service
                port:
                  number: 80