---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      serviceAccountName: KUSTOMIZE_SHARED_SVC_ACCOUNT_NAME
      automountServiceAccountToken: true
      containers:
      - name: user-management
        image: KUSTOMIZE_IMAGE
        ports:
        - containerPort: 8001
          name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  selector:
    app: user-management
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8001
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-management-service-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: KUSTOMIZE_API_HOST
      http:
        paths:
          - backend:
              service:
                name: user-management-service
                port:
                  number: 80
            path: /users
            pathType: Prefix
